### ISSUE TITLE
Faild to install from Hackage

### ISSUE THREAD

**Issue by rosenk** [chrisdone/intero#11]
$ cabal install ghci-ng
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghci-ng-7.6.3.5 (user goal)
next goal: base (dependency of ghci-ng-7.6.3.5)
rejecting: base-4.7.0.2/installed-95e... (conflict: ghci-ng => base>=4.6 &&
<4.7)
rejecting: base-4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0,
4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0,
4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed instance)
Dependency tree exhaustively searched.

**Comment by cocreature** [comment]
You're trying to install a different ghci-ng (that is quite outdated). This one is not (yet?) on hackage as there is a bug causing hackage to interpret the `-dynamic` flag incorrectly. For the time being you need to install manually.

**Comment by angerman** [comment]
Whom would we have to talk to, and offer assistance, to make hackage support `-dynamic`?

**Comment by cocreature** [comment]
Probably directly to the hackage guys https://github.com/haskell/hackage-server, but I'm really the wrong person to answer such questions, I just repeated what chrisdone told me when I asked him about it :)

**Comment by angerman** [comment]
Alright, I'll see if I can find someone, and cajole them into helping out here :)

So far it seems that we have
A cabal fix haskell/cabal#2329 (that landed in cabal 1.22)
Which in turn requires package to be updated: haskell/hackage-server#308

This would in turn allow `ghci-ng` to end up on package. And pave the way
for a `ghci-ng` haskell layer in spacemacs: syl20bnr/spacemacs#346.
