### ISSUE TITLE
:type-at does not include the constraint for a type

### ISSUE THREAD

**Issue by meditans** [chrisdone/intero#14]
Hi, when I use the function haskell-mode-show-type-at on `f` here:

    module Why where
    f x = x * 2

I get a type for f which is `f :: a -> a`. It's true that I get the right type with the info command, but, as I often use C-u C-t to insert the inferred type, I wonder what is the reason for this behaviour.

**Comment by chrisdone** [comment]
For some reason sub-types aret coming back with constraints missing.

**Comment by DanielG** [comment]
Something to do with -XScopedTypeVariables maybe?

**Comment by chrisdone** [comment]
They're skolem types. Needs more investigation into the GHC API.

**Comment by chrisdone** [comment]
Fixed!
