### ISSUE TITLE
[Question] +c features and usage

### ISSUE THREAD

**Issue by geraldus** [chrisdone/intero#19]
Hey, Chris!
I'm working on asynchronous company backend, which fetch completions from current Haskell process, using `:complete` command. I want to have something similar as `company-ghc` for `ghc-mod` users in the end. So I want to have module name from where completion comes from  as annotations and completion type information as meta. Currently the only way I can think of is to asynchronously invoke `:info` for each completion candidate, but I suppose this will take too long time.

So can I somehow use `:set +c` for get completions with module information and types at once?

**Comment by chrisdone** [comment]
Going back to the drawing board on this project, closing for now.
