### ISSUE TITLE
Fix support for find-uses for definitions

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/intero#2]
![screenshot from 2014-12-11 18 27 06](https://cloud.githubusercontent.com/assets/320177/5404954/8c3339be-8163-11e4-8968-cf36e42bc264.png)

Running haskell-mode-find-uses on the type or data constructor for `Hughes` only highlights the new type, pressing `<TAB>` and the like doesn't go anywhere.

Am I doing something wrong?

**Comment by chrisdone** [comment]
Dupe of #3, closing.
