### ISSUE TITLE
Can't build on Windows due to missing dynamic libraries

### ISSUE THREAD

**Issue by conklech** [chrisdone/intero#22]
Building `ghci-ng` `master` on Windows with GHC 7.8.3 (HP 2014.2) fails catastrophically:

    ghc\Main.hs:70:8:
        Could not find module `Data.List'
        Perhaps you haven't installed the "dyn" libraries for package `base'?
        Use -v to see a list of the files searched for.

And similarly for every other import.

This is because `ghci-ng` is built with `-dynamic`, which apparently is unavailable on Windows. See [GHC trac ticket 8828](https://ghc.haskell.org/trac/ghc/ticket/8228), although I can't find any clear documentation on the situation. (I thought dynamic builds used to work?)

Has anybody successfully built `ghci-ng` on Windows? I don't think this is an issue with `ghci-ng` itself, but I wanted to check, and document this failure.

**Comment by conklech** [comment]
Removing `-dynamic` from the build options results in successful compilation of a binary that apparently works. I haven't (yet?) tested it extensively.

What problems would be expected from a non-dynamic ghci-ng?

**Comment by chrisdone** [comment]
Without `-dynamic` on GHC 7.8 there are delicious dynamic linker errors when trying to load things in. It took a long time to narrow down.

**Comment by conklech** [comment]
Darn. Same story on 7.10? 

Do you have any suggestions for things/people I could poke at to get this problem resolved (or at least documented)?

**Comment by chrisdone** [comment]
I expect on 7.10, too, as it came with the new linker support in 7.8. I think the solution is not to use the haskell platform, really. You should get profiling libs with your GHC, it's cheeky that they weren't available. Using MinGHC or Stack might be easier.

**Comment by conklech** [comment]
I am using stack, using the default  32-bit ghc tarball. I don't know if I
tested with minghc. Hmm.

**Comment by chrisdone** [comment]
The GHC that stack downloads has no dynamic libs?

**Comment by chrisdone** [comment]
Yeah, try minghc.

**Comment by conklech** [comment]
Same result with minghc 7.10 32-bit. Boo. Did GHC really break `-dynamic` on windows with 7.8? That seems like an uncharacteristic regression.

    > cat DynamicTest.hs
    main = putStrLn "test"
    > ghc -dynamic DynamicTest.hs
    Could not find module `Prelude'

**Comment by jaccokrijnen** [comment]
Is there anything I could do to help get a working ghci-ng on Windows? Maybe (I have no experience with this) it is possible to build ghci-ng for windows by crosscompiling?

**Comment by conklech** [comment]
I don't expect cross compiling to be easier.

You might reach out to the GHC team to work out whether they can start
distributing dynamic libraries on windows again. I didn't get around to
talking with them about it.
