### ISSUE TITLE
Do not build on NixOS.

### ISSUE THREAD

**Issue by Pitometsu** [chrisdone/intero#23]
Do not build on [NixOS](https://github.com/NixOS/nixpkgs/issues/10897)
```
Preprocessing executable 'ghci-ng' for ghci-ng-7.6.3.5...

ghc/Main.hs:43:8:
    Could not find module ‘StaticFlagParser’
```
http://packdeps.haskellers.com/feed?needle=ghci-ng

**Comment by cocreature** [comment]
This repo is not the same as the version on hackage and the version on hackage is no longer maintained (all the features went into ghci afaik) so use the master branch or stay with standard ghci.

**Comment by Pitometsu** [comment]
@cocreature thank you, so issue perhaps may be closed.
