### ISSUE TITLE
Feature request: Support issuing commands to a running ghci process from the command line

### ISSUE THREAD

**Issue by schell** [chrisdone/intero#24]
I'd like to build an ad-hoc hot loader and it seems like the ability to inject ghci commands from a separate process would be a pretty cool feature. Maybe there's already support for this somewhere?

**Comment by chrisdone** [comment]
No plans for this at present. Going back to design phase on this.

**Comment by schell** [comment]
Thansk for the update. Is the design process public? Just curious. :)
