### ISSUE TITLE
:type-at not working with spaces in filename

### ISSUE THREAD

**Issue by cobalamin** [chrisdone/intero#25]
Output from the haskell-process-log in Emacs, using ghci-ng through stack-ghci, after running `haskell-mode-show-type-at`:

```
-> :type-at /Users/chipf0rk/dev/Learning/Haskell Programming/Ch23/src/Lib.hs 28 18 28 25 randomR

<- Expected integer in  Programming/Ch23/src/Lib.hs 28 18 28 25 randomR
```

It seems that there's very simple parsing going on here that just splits on spaces, since manually executing the command with the whole path wrapped in double quotes doesn't fix the problem.

**Comment by chrisdone** [comment]
We're going to expose a JSON API for this instead so that we don't need ad-hoc parsing.

**Comment by chrisdone** [comment]
Fixed!
