### ISSUE TITLE
Make better error message for :type-at, :uses and :loc-at

### ISSUE THREAD

**Issue by rvion** [chrisdone/intero#28]
:type-at produces a strange error message when given wrong params
Also, a newline is missing

```
*Test> :type-at
Expected integer in *Test>
```

**Comment by rvion** [comment]
for consistency, here is the current output given by :type

```
*Test> :type

<no location info>: not an expression: ‘’
*Test>
```

**Comment by chrisdone** [comment]
I think we can rename this to: make better parser error for `:type-at`, `:uses` and `:loc-at`. :+1:

**Comment by chrisdone** [comment]
I think we can just have a message which outputs the command description (`:type-at file line-1 col-1 line-2 col-2 "alt"`).

**Comment by chrisdone** [comment]
Also make the string an optional argument, as it's more useful for editors as a fallback.
