### ISSUE TITLE
Make :type-at return types of containing expressions if bounds contain no expression

### ISSUE THREAD

**Issue by rvion** [chrisdone/intero#29]
I have a module `Test.hs`

```haskell
module Test where

test :: IO ()
test = putStrLn "ok"
```

and I want to use `type-at` to get the type of things I select in my editor, as you can see in the following pictures:

here, I select the letter `S`:
![image](https://cloud.githubusercontent.com/assets/2150990/15269598/107d266e-1a04-11e6-99f0-a157a4fa5f4c.png)

Support this in Intero.

**Comment by chrisdone** [comment]
The `<text>` part is supposed to be for identifiers. Let's include this in #28 as "make better docs". 

It's for when you've moved your code around but you want to get type info of e.g. `putStrLn`, if the location is out of date and the string is now `rLn "blah` then that's no type info. Instead, you provide the alt string so that it can lookup that.

In the case of the user typing it out, we can make it an optional argument.

**Comment by rvion** [comment]
@chrisdone: the <text> part is not the main problem I see.

The main problem I have in this issue is that __`:type-at` doesn't return type of sub-expressions as shown in the image.__ (regardless of text)


the real title of this issue should have been __:type-at doesn't return the type of the closest enclosing expression, but fails when given a sub-expression__

Am I missing something ? 
Should we re-open the issue ?

regarding making "text" optional, I agree.

**Comment by chrisdone** [comment]
Okay, I'll edit the issue and re-open.

**Comment by rvion** [comment]
in other words, my problem is that I can't reproduce pictures above (produced with `ghc-mod`) with `intero` because `intero` doesn't seem to be able to handle sub-expressions.

Having the ability to get instant feedback in an editor when selection change allow powerfull (mouse-free) workflow. 

eg: it gives you the ability to quickly expand the selection to the left while coding to see the type of next arguments you need to provide.

**Comment by rvion** [comment]
@chrisdone I see you edited the original message. 
(I have no problem with that, feel free to edit / remove messages from this thread to clean it up)

I just want to add that the picture you kept is rather easy to implement, but there is more complex cases like this one:

![image](https://cloud.githubusercontent.com/assets/2150990/15269736/16834ab6-1a09-11e6-8535-382f2131650f.png)
(here, I select `" "`)

**Comment by chrisdone** [comment]
Sure, I understood the meaning of the issue now. Intero is stricter because I use structured-haskell-mode which can select the exact bounds of an expression on a key press. But it's pretty straight-forward to add this for "free selection". 

I added a pending test.

**Comment by chrisdone** [comment]
> I just want to add that the picture you kept is rather easy to implement, but there is more complex cases like this one:

> ![image](https://cloud.githubusercontent.com/assets/2150990/15269736/16834ab6-1a09-11e6-8535-382f2131650f.png)
(here, I select `" "`, and ghc-mod detect that the `smallest enclosing expression` is `concat3 "aa" "bb"`) 

That behaviour seems kind of weird. I'd expect such a random selection to yield the type `String`.

**Comment by rvion** [comment]
@chrisdone I promise you it is a very powerfull feature as is. It allows you to get the exact context you need within a few keystrokes, always. From experience, it is much better than `get type of expression`.

All people I showed the feature used it from day one to explore code much faster.

I agree that the above picture is quite tricky, but the behaviour is very pleasant, and hard forget once you try it. 

an other way to think of it is

what are the list of enclosing expression ? 

 - concat3 "aa" "bb" 
 - concat3 "aa" "bb" "cc"
 - (concat3 "aa" "bb" "cc")
 - putStrLn (concat3 "aa" "bb" "cc")

what is the smaller one ?

 - concat3 "aa" "bb" 

what is it's type ?

 - String -> String

**Comment by chrisdone** [comment]
I think maybe your screenshot is just out of date. The type signature in your screenshot is `String -> String -> String`, so the type of `concat3 "aa" "bb"` is `String`. 

I understand how the feature is supposed to be, though.

**Comment by rvion** [comment]
... -__-'

my bad, correct screenshot is:
![image](https://cloud.githubusercontent.com/assets/2150990/15269839/0efffc1e-1a0c-11e6-810b-133e56baf617.png)
here, I select `" "`, and ghc-mod detect that the smallest enclosing expression is `concat3 "aa" "bb"`that have type `String -> String`

**Comment by chrisdone** [comment]
I added a `pendingWith` here: https://github.com/chrisdone/intero/blob/master/src/test/Main.hs#L97

For anyone reading who's interested in this feature before I get round to it, the place to implement would simply be here: https://github.com/chrisdone/intero/blob/master/src/GhciFind.hs#L264

I can't really do any programming over the weekend, but I'll be able to get to it on Monday.

**Comment by rvion** [comment]
thanks 

------------

An other way to imagine how this feature can be useful is to imagine this current workflow

1. select a function name, see the type of the function
2. expand selection 1 character to the right, and see the background color (enclosing expression) expand automatically to the end of the next argument you start to select. you visually "see" the AST, and have direct feedback on how type inference changed the context.

For people who don't have a structured editor (so for everyone not using structured-haskell-mode :) ) this helps a lot :)

**Comment by chrisdone** [comment]
So I had a bit of time. Done!

**Comment by rvion** [comment]
nice! I'll check it right away

-------
btw you wrote the test as

```haskell
(typeAt "foo = 'a'" (1,1,1,1,"f") "f :: Char\n")
```
but shouldn't it be 
```haskell
(typeAt "foo = 'a'" (1,1,1,1,"f") "foo :: Char\n")
                                   ^^^
```
