### ISSUE TITLE
:uses doesn't work on types

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/intero#3]
Find uses on a type constructor currently doesn't work.

**Comment by chrisdone** [comment]
Seems like this has worked for some time, but I added some regression tests for it: https://github.com/chrisdone/intero/blob/054881388a5e3f0ef318cf4fe2fdad29c1893b36/src/test/Main.hs#L210

**Comment by bitemyapp** [comment]
@chrisdone awesome, thank you.
