### ISSUE TITLE
:complete for module-local defined names

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/intero#31]
We're currently using `:complete` but it only works in `interpreted` mode, for the much faster `-fobject-code` mode, it fails to load the module in context.

We need to:

1. Enable interpreted mode after a successful `.o` load, and reload temporarily to get the context. Or better: This is probably not necessary if we can look at all names in scope, a la `:loc-at`.
2. Also use `mod_infos` for completion of definition-local bindings.

**Comment by obadz** [comment]
```
λ> fol[Tab]
```
⇒ nothing happens. Would expect to be shown `foldl`, `foldr`, etc. like in ghci.

Is this what this issue refers to or do I need to open a separate one?

**Comment by chrisdone** [comment]
That's a separate issue. I may have broken that.
