### ISSUE TITLE
Can't use intero on its own repo

### ISSUE THREAD

**Issue by obadz** [chrisdone/intero#36]
(Can't use ghci either though..)

```
$ cabal repl --with-ghc=intero
Preprocessing executable 'intero' for intero-0.1.8...
Intero 0.1.8 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

/nix/store/86nvh9qjd4ny2cb9l9zqg8fzhxdra596-binutils-2.26/bin/ld: dist/build/intero/intero-tmp/cbits/hschooks.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
dist/build/intero/intero-tmp/cbits/hschooks.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

Same message if I just `cabal repl` (with ghci…)

I've tried peppering some `-fPIC` in the `.cabal` file to no avail.

Have not seen this problem on any other repos. I'm on very recent NixOS.

**Comment by chrisdone** [comment]
stack ghci --with-ghc works for me

**Comment by chrisdone** [comment]
I think it's just tricky to load GHCi within itself. Sometimes it works, sometimes not.

**Comment by chrisdone** [comment]
Closing in favor of #43 which has a more generic title people can pick up on.
