### ISSUE TITLE
Type info not collected for `:add`-ed modules

### ISSUE THREAD

**Issue by mgsloan** [chrisdone/intero#37]
Repro:

1) Run `stack ghci --with-ghc intero` in the stack repo (perhaps with `--no-build` if it's already been built)
2) Try `:all-types` and get no results
3) Do a `:load Main`
4) Now `:all-types` yields all types

The difference is that the ghci-script generated by stack uses `:add`.

**Comment by mgsloan** [comment]
Opened a PR which seems to address this.

**Comment by chrisdone** [comment]
Think we can close this now.
