### ISSUE TITLE
Use interrobang for default prompt

### ISSUE THREAD

**Issue by mgsloan** [chrisdone/intero#40]
Bit of a playful suggestion!  When unicode is supported by the terminal, use an interrobang (`‽`) for the prompt.  This makes sense because while the focus of `intero` is adding more queries (`?`), the prompt is also used to execute commands (`!`).  The two together is the interrobang‽‽‽

**Comment by chrisdone** [comment]
I like this, it's cute and unique!

**Comment by mgsloan** [comment]
\o/ I didn't realize this would be an emacs change, but I suppose that's better than assuming a unicode terminal.

I was going to suggest borrowing the unicode detection code from stack: https://github.com/commercialhaskell/stack/blob/master/src/Stack/Types/StackT.hs#L111

But it turns out that stack borrowed it form GHC!  So it should be available.  Anyway, no big deal :)
