### ISSUE TITLE
Wrong $PWD for Template Haskell code with multiple Stack packages

### ISSUE THREAD

**Issue by koterpillar** [chrisdone/intero#512]
I have more than one package in a Stack project, in different directories:

```yaml
packages:
- '.'
- 'another_package'
```

In `another_package/src/Mod.hs`, I reference a file from a QuasiQuoter:

```haskell
{-# LANGUAGE QuasiQuotes #-}
module Mod where

import Data.String.Here

someVal = [hereFile|src/IncludedFile.txt|]
```

File `another_package/src/IncludedFile.txt` exists. The code in `Mod.hs` gets compiled fine by Stack, and the contents of `IncludedFile.txt` is reflected in `someVal`.

However, Intero complains:

```
     • Exception when trying to run compile-time code:
         src/IncludedFile.rq: openFile: does not exist (No such file or directory)
       Code: Language.Haskell.TH.Quote.quoteExp
               hereFile "src/IncludedFile.txt"
     • In the quasi-quotation: [hereFile|src/IncludedFile.txt|] (intero)
```

**Comment by mgsloan** [comment]
Solving this perfectly is an upstream ghc issue: https://ghc.haskell.org/trac/ghc/ticket/10827

Recommended resolution for now is to use https://www.stackage.org/haddock/lts-10.3/th-utilities-0.2.0.1/TH-RelativePaths.html

**Comment by koterpillar** [comment]
I suspected that it would be an upstream issue. I'm wondering if it makes sense to keep one intero process per package?

**Comment by koterpillar** [comment]
I suspected that it would be an upstream issue. I'm wondering if it makes sense to keep one intero process per package?

**Comment by mgsloan** [comment]
Hmm, maybe it would be good to have an option for that.  It would be an expensive default, though.

**Comment by chrisdone** [comment]
Use the available relative dir options with TH to avoid being PWD-dependent.

**Comment by chrisdone** [comment]
Figured this out. We just need to search for the `stack.yaml` instead of the `.cabal` file, and in the path, we specify the package path.

**Comment by chrisdone** [comment]
Use this:

```haskell
import System.Directory
import System.FilePath

findProjectFile :: FilePath -> IO FilePath
findProjectFile relativeFile =
  do mstack <- findStack
     case mstack of
       Nothing -> error "Could not find stack.yaml."
       Just stackDir -> pure (stackDir <> "/" <> relativeFile)

findStack :: IO (Maybe FilePath)
findStack = do
  pwd <- getCurrentDirectory
  go pwd
  where
    go pwd = do
      exists <- doesFileExist (pwd <> "/stack.yaml")
      if exists
        then pure (Just pwd)
        else let parent = takeDirectory pwd
             in if parent /= pwd
                   then go parent
                   else pure Nothing
```

Example:

```haskell
> findProjectFile "prana-primops/primops.txt"
"/home/chris/Work/chrisdone/prana/prana-primops/primops.txt"
```

**Comment by chrisdone** [comment]
Reason: using the .cabal file is unreliable because in intero's case, the buffer's contents is copied to `$STACK_ROOT/.stack-work/tmp/..` and then `:load`'d. It doesn't know which package it's in right now.
