### ISSUE TITLE
Support for auto-generated Paths_pkgname module

### ISSUE THREAD

**Issue by gbrsales** [chrisdone/intero#525]
[This example package](https://github.com/gbrsales/intero_paths) contains a single executable accessing programatically its own version through the auto-generated `Paths_paths` module.

Stack correctly builds the project, while Intero marks the import of `Paths_paths` as an error (`Could not find module 'Paths_paths'`).

Is it possible to support `Paths_pkgname` modules?

**Comment by mgsloan** [comment]
This is a stack bug - the ghci code did not yet use the autogens paths used by cabal per-component build (Cabal > 2).  I have a PR here that should be merged soon which resolves it - https://github.com/commercialhaskell/stack/pull/3795

**Comment by chrisdone** [comment]
Stack PR merged.
