### ISSUE TITLE
Intero REPL autocomplete problem

### ISSUE THREAD

**Issue by joswik** [chrisdone/intero#529]
Selecting a Language extension in the REPL from dropdown menu removes all text before it:
e.g: 
λ :set -XOv (RET)
  you get this:
λ -XOverloadedStrings

It doesn't happen in a regular haskell source code buffer 
i.e. {-# LANGUAGE OverloadedStrings #-} autocompletes fine.

Tested with the latest intero (20180221.149),
Emacs 25.2, GHC 8.0.2 (Win7 32-bit), and
Emacs 25.3, GHC 8.2.2 (Mac 10.12.6) - with only intero and stack installed.

**Comment by chrisdone** [comment]
Doesn't reproduce for me, must've been fixed by #530.

**Comment by joswik** [comment]
Yes, it's  been working correctly for a long time.

Thanks
Josko
________________________________
