### ISSUE TITLE
Disable syntax error highlighting when using a source file to live code?

### ISSUE THREAD

**Issue by lnfiniteMonkeys** [chrisdone/intero#537]
Hi, I'm using intero to develop a live-coding environment for music composition and performance and I love it to bits, however I have a small problem: I want to be able to define and call functions in the same file, using it as a mix between source file and REPL. 

I can already do something like "someFunc n = n*2" and then underneath it write "someFunc 2", evaluate it with C-c C-c and get the result. However, the function call is (rightly) highlighted as a syntax error and the focus is moved from the source window to the REPL window. Is there a way to disable these features when I'm using intero to live code, instead of just writing source code?

The functionality that I'm going for is this: https://www.youtube.com/watch?v=S_UZXmtMenE. I could copy the .el file that's used in the video, but then I would be missing out on all the other wonderful intero features!

**Comment by chrisdone** [comment]
I feel like this requires a special mode. 

When you're doing a live coding session, what intero features do you use?

It's of course trivial to send a random region to the REPL, but how do you deal with wanting to write top-level expressions?
