### ISSUE TITLE
`PackageImports` support

### ISSUE THREAD

**Issue by joneshf** [chrisdone/intero#554]
I can't seem to figure out `PackageImports`. If I have a library, and import it somewhere else–an executable or test–`intero` seems to fail.

![screenshot-1526525454](https://user-images.githubusercontent.com/1356417/40154679-670732fa-5944-11e8-9cb1-aadc6e34f65e.png)

I made a repo as small as I could that would make the failure: https://github.com/joneshf/intero-package-imports

Am I doing something wrong?
Are `PackageImports` supported?

**Comment by joneshf** [comment]
> It should be possible to do a stack build of the library and then set the intero target to just the exe component.

That works! Thanks so much!

I'd have never guessed to do that. Where should this work around be documented? I'm down to submit a PR.

**Comment by joneshf** [comment]
Hmm, this seems to fail if I'm wanting to use the library now. I.e. if the target is set to just the executable, none of the dependencies are found for the library. Is there a way for `intero` to work in both situations: working inside the library and working inside the executable?

**Comment by chrisdone** [comment]
Just setting your targets with `M-x intero-targets` is the only way to configure which targets (libs, exes, tests, benches) are loaded.
