### ISSUE TITLE
Getting "ghc: panic!" in intero buffer when trying to evaluate value in IO using ghc 8.4.3

### ISSUE THREAD

**Issue by alexpeits** [chrisdone/intero#569]
While in an intero ghci buffer, if I try to evaluate something of type `IO a`, where `a` is an instance of `Show`, so it *can* be printed, I get the following error:

File:

```
module Test where

test :: IO String
test = return "test"
```

intero ghci buffer (after loading the file):
```
-- Works
> x <- test
> x
"test"

-- Doesn't work
> test
ghc: panic! (the 'impossible' happened)
  (GHC version 8.4.3 for x86_64-unknown-linux):
	nameModule
  system $dShow_a1UI
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:1150:37 in ghc:Outputable
        pprPanic, called at compiler/basicTypes/Name.hs:241:3 in ghc:Name

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

This occurs using intero 0.1.32, ghc 8.4.3, stack 1.7.1 on debian linux.

This does *not* happen when using a regular ghci in the terminal, so I am unsure if it is an intero or ghc bug.

**Comment by konn** [comment]
Same here, with GHC 8.4.3, intero 0.1.32 and stack 1.7.1 on macOS High Sierra 10.13.6.

**Comment by tazjin** [comment]
This is fixed in any given GHCI session by doing `:set -fno-defer-out-of-scope-variables`, but I haven't figured out how to always pass that. It seems like putting it in a `.ghci` file has no effect.

**Comment by tazjin** [comment]
None of the settings related to passing GHCi options seem to be capable, for some reason, of setting `-fno-defer-out-of-scope-variables`.

To avoid spending too much time on this I've added the following hack to my Emacs configuration to sort of fix it until GHC 8.6 is released with the upstream fix.

```lisp
(defun intero-fix-ghci-panic ()
  "Disable deferring of out of scope variable errors, which
  triggers a bug in the interactive Emacs REPL printing a panic
  under certain conditions."

  (interactive)
  (let* ((root (intero-project-root))
         (package-name (intero-package-name))
         (backend-buffer (intero-buffer 'backend))
         (name (format "*intero:%s:%s:repl*"
                       (file-name-nondirectory root)
                       package-name))
         (setting ":set -fno-defer-out-of-scope-variables\n"))
    (when (get-buffer name)
      (with-current-buffer (get-buffer name)
        (goto-char (point-max))
        (let ((process (get-buffer-process (current-buffer))))
          (when process (process-send-string process setting)))))))

;; Brute-force fix: Ensure the setting is injected every time the REPL
;; is selected.
;;
;; Upstream issue: https://github.com/commercialhaskell/intero/issues/569

(advice-add 'intero-repl :before (lambda (&rest r) (intero-fix-ghci-panic))
            '((name . intero-panic-fix)))
(advice-add 'intero-repl-load :before (lambda (&rest r) (intero-fix-ghci-panic))
            '((name . intero-panic-fix)))
```

**Comment by tazjin** [comment]
@konn Small addition: I realised it makes more sense to use `:after` instead of `:before` as the advice position (so that it runs correctly in case the REPL is just being started).

Personally I find the defaulting to deferring errors a bit annoying (also for type errors), it'd be nicer if that was opt-in.

**Comment by maruks** [comment]
it happens in ghc 8.4.3 too   
has anyone fixed this problem?

**Comment by chrisdone** [comment]
I'm also reproducing this. Intero for Emacs launches `ghci` for the REPL, so this technically isn't an intero bug.

However, the repl [is launched with `-fdefer-type-errors`](http://github.com/chrisdone/intero/commit/df98fd39e57f11067ad932d3a452c12f430116b9). I propose that I just comment out that line for the REPL launcher, with a link to this issue.
