### ISSUE TITLE
Freezes and blacklist not working

### ISSUE THREAD

**Issue by simendsjo** [chrisdone/intero#578]
Emacs freeze for a couple of seconds a second after the cursor stops moving. The problem goes away when disabling intero. I have version `;; Package-Version: 20180806.2145`.

I don't intend to use intero for this project at all, but I'm unable to blacklist it. I've tried

``` emacs-lisp
  (setq intero-blacklist '("/home/simendsjo/code/haskell/base/" "/home/simendsjo/code/haskell/ghc" "~/code/haskell/ghc")) ;; yes, I've tried both with and without ~
  (add-hook 'haskell-mode-hook 'intero-mode-blacklist) ;; seems this is deprecated
  (intero-global-mode) ;; but using this instead doesn't seem to work either
```

Not sure if these issues are related, but I haven't noticed freezes like this for projects where intero works.

**Comment by simendsjo** [comment]
I cannot see any intero-mode in the hooks, but then again, I'm an emacs newbie and using spacemacs which might have magic I'm unable to locate.

`haskell-mode-hook’s value is (spacemacs//init-jump-handlers-haskell-mode)`

From the init-jump-handlers-haskell-mode function:
`(setq haskell-modes '(haskell-mode literate-haskell-mode))`

**Comment by simendsjo** [comment]
Could it be this line in my config: `(setq haskell-completion-backend 'intero)`?
I see this in the spacemacs haskell setup:

``` emacs-lisp
(when (configuration-layer/package-usedp 'company)
    (pcase haskell-completion-backend
      (`ghci (spacemacs-haskell//setup-ghci))
      (`ghc-mod (spacemacs-haskell//setup-ghc-mod))
      (`intero (spacemacs-haskell//setup-intero)))))
```

And the `setup-intero` function:

``` emacs-lisp
(defun spacemacs-haskell//setup-intero ()
  (add-to-list 'company-backends-haskell-mode
               '(company-intero company-dabbrev-code company-yasnippet))
  (push 'intero-goto-definition spacemacs-jump-handlers)
  (intero-mode)
  (dolist (mode haskell-modes)
    (spacemacs/set-leader-keys-for-major-mode mode
      "hi" 'intero-info
      "ht" 'intero-type-at
      "hT" 'haskell-intero/insert-type
      "rs" 'intero-apply-suggestions
      "sb" 'intero-repl-load))
```

Notice the `(intero-mode)` line here. I found that removing `(setq haskell-completion-backend 'intero)` from my config seems to work, but on the other hand, it seems strang that `(intero-mode)` doesn't honor `intero-blacklist`.

**Comment by chrisdone** [comment]
`intero-mode` is a standard Emacs way of starting a mode. You shouldn't reasonably try to start a mode and have the mode throw an error, that's a bad failure case. Instead, we have `intero-global-mode` which uses `intero-mode-maybe` which maybe or maybe not enables `intero-mode`.

So spacemacs is at fault here. I've added a suggestion to that spacemacs issue to help them resolve it.
