### ISSUE TITLE
The Intero custom stack command doesn't work with a custom Prelude

### ISSUE THREAD

**Issue by theophile-fl** [chrisdone/intero#579]
Hi! I'm using Intero from Spacemacs with a [custom Prelude](https://github.com/kowainik/relude) in my project. Whenever I start Intero, I get this error:

```
<interactive>:1:1: error:
    attempting to use module ‘main:Prelude’ (/home/theophile/dev/polynot-twitter/lib/Prelude.hs) which is not loaded
```
Can someone enlighten me on this issue? How can I fix this?

**Comment by wedens** [comment]
I experience the same problem using `base-noprelude` and custom `Prelude.hs` without `NoImplicitPrelude` extension.

**Comment by tkadur** [comment]
Has anyone found a solution to this? It doesn't appear to have been fixed or addressed in any way and not being able to use `intero` with any project using a custom prelude is a huge drag.

**Comment by chrisdone** [comment]
Do you reproduce this with `ghci`?

**Comment by tkadur** [comment]
I assume you mean when running `stack ghci --with-ghc intero`? If so, yes. Here's the output:

```
$ stack ghci --with-ghc intero
Using main module: 1. Package `project' component exe:project-exe with main-is file: /path/project/app/Main.hs
project-0.1.0.0: configure (lib + exe)
Configuring project-0.1.0.0...
project-0.1.0.0: initial-build-steps (lib + exe)
The following GHC options are incompatible with GHCi and have not been passed to it: -Werror -threaded
Configuring GHCi with the following packages: project
Intero 0.1.35 (GHC 8.6.3)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 55240

<interactive>:1:1: error:
    attempting to use module ‘main:Prelude’ (/path/project/src/Prelude.hs) which is not loaded

```

**Comment by chrisdone** [comment]
Nope, just regular `ghci` as a base test. If it doesn't work with `ghci` then there's little hope of it working with `intero` (although miracles happen).

**Comment by tkadur** [comment]
Yeah, `stack ghci` works.

```
$ stack ghci
Using main module: 1. Package `project' component project-exe with main-is file: /path/project/app/Main.hs
project-0.1.0.0: initial-build-steps (lib + exe)
The following GHC options are incompatible with GHCi and have not been passed to it: -Werror -threaded
Configuring GHCi with the following packages: project
GHCi, version 8.6.3: http://www.haskell.org/ghc/  :? for help
[ 1 of 19] Compiling Prelude          ( /path/project/src/Prelude.hs, interpreted )
...
[19 of 19] Compiling Main             ( /path/project/app/Main.hs, interpreted )
Ok, 19 modules loaded.
λ>

```

**Comment by chrisdone** [comment]
What’s a git project that I can clone and run `stack ghci` on?

**Comment by mkawalec** [comment]
I am getting the same error when using a custom prelude, unfortunately not in public code.

**Comment by jgertm** [comment]
@chrisdone, you should be able to reproduce the issue with https://github.com/jgertm/lang
I get the same error when trying to start `intero`.
`stack ghci` works fine.

**Comment by wraithm** [comment]
Any solution to this? @theophile-fl @mkawalec @jgertm @tkadur Did you end up doing something different?

**Comment by theophile-fl** [comment]
I switched to Neovim + HIE nowadays :/

**Comment by theophile-fl** [comment]
I'm closing this issue since it seems it's not going anywhere soon
