### ISSUE TITLE
Intero stuck at showing type info

### ISSUE THREAD

**Issue by colinxy** [chrisdone/intero#602]
## Problem

Intero is stuck at showing type info for a simple haskell file.

- [X] I checked the issue tracker for existing issues about this problem.
- [X] I'm using the latest version of intero.
- [X] I am not using Nix, which is notorious for breaking stack, intero and lots of other things.
- [X] I have checked that my error is not GHC's fault by testing my project on standard GHCi.
- [X] I am using calm, polite language.
- [X] I am not trying to use intero on bleeding edge GHC (head or nightly); Intero is only developed against full GHC releases.

### Input program/project

```
doubleMe x = x + x
```

Navigate the cursor to `doubleMe` and hit `C-c C-t` or `M-x intero-type-at`.

### Expected behavior

Show type info.

### Actual behavior

Emacs is stuck and spinning at 20% cpu, but intero process is idle. Debug info for intero shows: `Connected to service, sending ":type-at \"/home/colinxy/.stack/global-project/.stack-work/intero/intero2iattx-TEMP.hs\" 1 1 1 9 \"doubleMe\""`

**Comment by rrudakov** [comment]
The same thing on calling `intero-goto-definition`.

**Comment by chrisdone** [comment]
Is this a recent regression?

**Comment by chrisdone** [comment]
Also, what OS are you both on?

**Comment by chrisdone** [comment]
OK, it was that I was calling `hGetEncoding` on stdin which apparently causes a freeze; instead I called it on `stdout` and that works correctly.  I've uploaded the fix to hackage as `intero-0.1.38`.

Please wait ~30 minutes for stackage to update, then update your emacs package so that `intero-package-version` is at 0.1.38. :+1:

**Comment by chrisdone** [comment]
When intero version 0.1.38 appears on https://www.stackage.org/package/intero you'll know it's updated.
