### ISSUE TITLE
Failed to display type error on Windows

### ISSUE THREAD

**Issue by ice1000** [chrisdone/intero#603]
## Problem

It's very easy to describe the issue so I'm not gonna split it into many sections.

OS: Windows 10, update 1809
Stack version: 1.9.1
GHC version: not related

0. Install via `stack install intero`
1. Start via `stack exec intero`
2. Type some simple ill-typed expressions like `1+'a'`
3. Reproduced!

```
λ> stack exec intero
Intero 0.1.37 (GHC 8.4.4)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 57601
λ> 1+'a'

<interactive>:1:1: error:
    *** Exception: <stderr>: hPutChar: invalid argument (invalid character)
λ>
```

What is `Exception: <stderr>: hPutChar: invalid argument (invalid character)`?
I suppose it's a bug.

Without intero, ghci gives friendly error message showing that it's ill-typed expression.

- [X] I checked the issue tracker for existing issues about this problem.
- [X] I'm using the latest version of intero.
- [X] I am not using Nix, which is notorious for breaking stack, intero and lots of other things.
- [X] I have checked that my error is not GHC's fault by testing my project on standard GHCi.
- [X] I am using calm, polite language.
- [X] I am not trying to use intero on bleeding edge GHC (head or nightly); Intero is only developed against full GHC releases.

**Comment by ice1000** [comment]
Even a simple `_` triggers this.

**Comment by ice1000** [comment]
```
$ intero --version
Intero 0.1.37
```

**Comment by purcell** [comment]
Duplicate of #602, I believe.

**Comment by ice1000** [comment]
@purcell Come on.

```
$ stack exec intero
Intero 0.1.38 (GHC 8.4.4)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 64869
Prelude> 1+'a'

<interactive>:1:1: error:
    *** Exception: <stderr>: hPutChar: invalid argument (invalid character)
Prelude> _

<interactive>:1:1: error:
    *** Exception: <stderr>: hPutChar: invalid argument (invalid character)
```

**Comment by ice1000** [comment]
Reproducible with 0.1.38:

```
$ stack exec intero
Intero 0.1.38 (GHC 8.4.4)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 64869
Prelude> 1+'a'

<interactive>:1:1: error:
    *** Exception: <stderr>: hPutChar: invalid argument (invalid character)
Prelude> _

<interactive>:1:1: error:
    *** Exception: <stderr>: hPutChar: invalid argument (invalid character)
```

Hope my language is polite. English is not my native language, sometimes I'm not aware of the language issue. Apologize for "Come on".

**Comment by ice1000** [comment]
0.1.38 is the new version introduced in 67e008e2462fa40216e4a2ec6566958531bd57c4.

https://github.com/chrisdone/intero/blob/67e008e2462fa40216e4a2ec6566958531bd57c4/intero.cabal#L4

**Comment by chrisdone** [comment]
@purcell Looks like this coincidentally is very similar to the other bug, but applies to the regular terminal which I didn't modify.

@ice1000 Can you test something out please? On your system run:

```
$ stack exec ghci
> import System.IO
> hGetEncoding stdout >>= print
```

and the same thing for intero:

```
$ stack exec intero
> import System.IO
> hGetEncoding stdout >>= print
```

I'd like to see what encoding `ghci` is using for `stdout`. And what `intero` is using.

**Comment by chrisdone** [comment]
On Linux it's working fine:

```
chris@precision:~$ stack exec intero --resolver ghc-8.4.4
Intero 0.1.34 (GHC 8.4.4)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 35255
Prelude> 1+'a'

<interactive>:1:1: error:
    • No instance for (Num Char) arising from a use of ‘+’
    • In the expression: 1 + 'a'
      In an equation for ‘it’: it = 1 + 'a'
```

```
Prelude System.IO> hGetEncoding stdout   
Just UTF-8
```

I suspend on Windows the encoding is either `Nothing` or something non-Unicodey.

**Comment by chrisdone** [comment]
We do have passing [Windows tests on appveyor](https://ci.appveyor.com/project/chrisdone/intero), so if we resolve this we can add a regression test. Maybe I can add a type error test to the test suite.

**Comment by ice1000** [comment]
It's `CP936`. I've never seen that..

**Comment by ice1000** [comment]
Thanks guys. I think I've found a workaround.

First, run `CHCP 65001` to change my cmd encoding to UTF-8. Then, intero works.

```
Active code page: 65001

C:\Users\ice10>stack exec intero
Intero 0.1.38 (GHC 8.4.4)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 64998
Prelude> 1+'a'

<interactive>:1:1: error:
    • No instance for (Num Char) arising from a use of ‘+’
    • In the expression: 1 + 'a'
      In an equation for ‘it’: it = 1 + 'a'
```

**Comment by ice1000** [comment]
What if we don't use the unicode character `•` when the cmd is not UTF-8?

**Comment by ice1000** [comment]
ghci will display `?` when the encoding is not UTF-8.

**Comment by ice1000** [comment]
Reference: https://ss64.com/nt/chcp.html

**Comment by chrisdone** [comment]
This error message comes from GHC's API, I don't have control over its contents.

Setting the right codepage in the terminal is fine, but you're not supposed to be using intero from the terminal anyway, so the question is what editor you're using to launch Intero, and what codepage the editor is setting, and whether you can control that.

**Comment by ice1000** [comment]
Oh.

My IDE is IntelliJ-IDEA with intellij-haskell plugin.

Thanks for the confirm.

**Comment by Ailrun** [comment]
@chrisdone Sorry for posting an additional comment on the closed issue.
How could I change codepage in emacs/intero?

**Comment by Ailrun** [comment]
I changed my whole window to use CP65001 (which is supported as a beta feature).
