### ISSUE TITLE
Error installling intero

### ISSUE THREAD

**Issue by jackwener** [chrisdone/intero#607]
## Question

fail to install intero

haskeline-0.7.5.0: configure
haskeline-0.7.5.0: build
Progress 1/2

--  While building package haskeline-0.7.5.0 using:
      /home/jakevin/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/jakevin/.stack/global-project/.stack-work/logs/haskeline-0.7.5.0.log

    Configuring haskeline-0.7.5.0...
    Preprocessing library for haskeline-0.7.5.0..
    /usr/bin/ld.gold：错误：cannot find -ltinfo
    collect2: error: ld returned 1 exit status
    linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_make.o failed (exit code 1)
    command was: /usr/bin/gcc .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_make.o .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_utils.o -o .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_make -fuse-ld=gold -fno-stack-protector -fuse-ld=gold -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/transformers-0.5.5.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/transformers-0.5.5.0 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/terminfo-0.4.1.2 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/terminfo-0.4.1.2 -ltinfo -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/stm-2.5.0.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/stm-2.5.0.0 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/process-1.6.3.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/process-1.6.3.0 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/directory-1.3.3.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/directory-1.3.3.0 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/unix-2.7.2.2 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/unix-2.7.2.2 -lrt -lutil -ldl -lpthread -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/time-1.8.0.2 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/time-1.8.0.2 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/filepath-1.4.2.1 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/filepath-1.4.2.1 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/containers-0.6.0.1 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/containers-0.6.0.1 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/bytestring-0.10.8.2 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/bytestring-0.10.8.2 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/deepseq-1.4.4.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/deepseq-1.4.4.0 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/array-0.5.3.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/array-0.5.3.0 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/base-4.12.0.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/base-4.12.0.0 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/integer-gmp-1.0.2.0 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/integer-gmp-1.0.2.0 -lgmp -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/ghc-prim-0.5.3 -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/ghc-prim-0.5.3 -L/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/rts -Wl,-R,/home/jakevin/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/lib/ghc-8.6.3/rts -lm -lrt -ldl -lpthread

**Comment by jackwener** [comment]
solved
`sudo apt install libtinfo-dev`

**Comment by Yuki-Minakami** [comment]
thanks!!!!!!!!!!
