### ISSUE TITLE
'stack build intero' stuck on cabal build

### ISSUE THREAD

**Issue by lautaroem1** [chrisdone/intero#613]
## Problem

I'm trying to get `intero` installed for IntelliSense on VSCode.
Previously, it worked with no problems, but now I'm trying to get it working on a new PC.

### Input program/project

This is inside a sample project created with `stack new hello-world simple`. Nothing changed.
The PC only has `stack` installed. No `cabal` , global `ghc` nor `Haskell Platform`. I'm using Windows 10 v1803.

### Expected behavior

Have `intero` installed.

### Actual behavior

When I run `stack build --copy-compiler-tool intero`, I get the next output:

```
random-1.1: download
haskeline-0.7.5.0: download
Cabal-2.4.1.0: download
random-1.1: configure
network-2.8.0.0: download
random-1.1: build
haskeline-0.7.5.0: configure
haskeline-0.7.5.0: build
network-2.8.0.0: configure
random-1.1: copy/register
syb-0.7: download
haskeline-0.7.5.0: copy/register
network-2.8.0.0: build
Cabal-2.4.1.0: configure
Cabal-2.4.1.0: build
syb-0.7: configure
syb-0.7: build
syb-0.7: copy/register
network-2.8.0.0: copy/register
Progress 4/7: Cabal-2.4.1.0
```

And it gets stuck there. Also, I get a `ghc.exe` process using over 2 GB RAM.

## Solution

If anyone is having the same problem, **just let it run**. I took mine over 20 minutes to finish.

**Comment by lautaroem1** [comment]
Please, can anyone mark this as "**Closed**"?

**Comment by chrisdone** [comment]
I can mark this as closed. But did you find the issue?

I also noticed with friends that `Cabal` got stuck. What gives?

**Comment by nh2** [comment]
@lautaroem1 I recommend building only `Cabal-2.4.1.0` so that you can see its build outputs scroll by, thus seeing whether there's a particular thing it's slow on (especially since your report is on Windows; my build of GHC itself seems to be ~24x slower on Windows than on Linux on the same machine, so this may be very worth investigating).

**Comment by lautaroem1** [comment]
@chrisdone I wasn't able to pin point the exact reason, but I think my SSD may be the cause: my write speeds are very low (40 to 80 Mb/s).
I'll replace my SSD in a few days and update the Issue with the new results.

**Comment by chrisdone** [comment]
I've discovered that Stack does not print output for `Cabal` and other packages like that. So it is actually building, but you don't get the output to see that. And Cabal has about 200 modules. It takes a looooong time to compile. Closing, assuming this is not an intero bug per se.
