### ISSUE TITLE
0.1.40 release request

### ISSUE THREAD

**Issue by k-bx** [chrisdone/intero#616]
Hi. Please release 0.1.40 that would work with GHC 8.6.5.

Thank you!

**Comment by parkerault** [comment]
Seconded (or sixthed); I can't complete installation of haskero because I'm a noob.

**Comment by develop7** [comment]
https://github.com/chrisdone/intero/pull/619 does the bump

**Comment by chrisdone** [comment]
Pushed 0.1.40 with GHC 8.6.5 bound.
