### ISSUE TITLE
Support for GHC 8.6.5

### ISSUE THREAD

**Issue by dharasim** [chrisdone/intero#618]
intero-0.1.39 has a specific constraint: ghc <= 8.6.4, which makes it refuse to self-install for ghc-8.6.5.

**Comment by develop7** [comment]
@chrisdone why does it have it anyway?

**Comment by chrisdone** [comment]
@develop7 because the GHC api is not a proper API with semantic versioning, things change all the time between minor versions and break things like intero. I'd prefer an upper bound restriction than a compile error.

**Comment by chrisdone** [comment]
0.1.40 is pushed with support for this.
