### ISSUE TITLE
Tabbing for alignment fails after a certain complex type signature

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [chrisdone/intero#621]
The comment in the last function (`meta`) at the bottom of [this module](https://github.com/JeffreyBenjaminBrown/vivid/blob/64454068d98adc1a4014d0c0752fd6eeb52ab491/src/Dispatch/Join.hs) illustrates the problem. In Emacs, if I uncomment the type signature for `ffxs`, and move the cursor to the next line (which defines `ffxs = ...`), pressing Tab will cause the line to jump around, but never to the place where I want it, which is four spaces in.

If I remove the newline from the type signature, the problem goes away.

**Comment by purcell** [comment]
Sounds like this is a haskell-mode issue, and nothing to do with intero, which doesn't do anything related to formatting or indentation.

**Comment by JeffreyBenjaminBrown** [comment]
Doh! Thanks, Steve!
