### ISSUE TITLE
Outdated Intero 0.1.39 for GHC 8.6.5 

### ISSUE THREAD

**Issue by schuermannator** [chrisdone/intero#622]
## Problem

When installed from MELPA, the default version for intero's autoinstall is still set to `0.1.39` which doesn't support GHC `8.6.5`. Since Intero `0.1.40` itself already supports GHC `8.6.5`, I simply upgraded the version to autoinstall in `intero.el` to fix. (related to #618 for supporting `GHC 8.6.5`)

### Input program/project

N/A

### Expected behavior

Successful autoinstall of `Intero 0.1.40` for `GHC 8.6.5`.

### Actual behavior

After install from MELPA, intero's init installs version `0.1.39` which results in a version mismatch with GHC `8.6.5` (upper bound at `8.6.4` I believe)

### Workarounds

Change version to `0.1.40` as set in `intero-package-version` in `intero.el`.

**Comment by JeffreyBenjaminBrown** [comment]
How is this done?  Intero is not working for me when I use GHC 8.6.5. It complains that it needs `haskeline` and maybe `tinfo` (complete error below). I added `haskeline` to my `.cabal` file, and I've already got `libtinfo-dev` installed, but still I get the same problem. 

When I run `list-packages` in emacs and then press `U`, I am informed that there are "no packages to upgrade". When I search my system for "intero.el" files, I find a lot of them:

```
jeff@jeff-Inspiron-5567:~/logic/hode$ sudo find / -name "intero.el"
[sudo] password for jeff:
/home/jeff/.stack/global-project/.stack-work/install/x86_64-linux/ghc-8.6.4/8.6.4/share/x86_64-linux-ghc-8.6.4/intero-0.1.38/elisp/intero.el
/home/jeff/.stack/global-project/.stack-work/install/x86_64-linux/ghc-8.2.2/8.2.2/share/x86_64-linux-ghc-8.2.2/intero-0.1.38/elisp/intero.el
/home/jeff/.stack/global-project/.stack-work/install/x86_64-linux/ghc-8.6.3/8.6.3/share/x86_64-linux-ghc-8.6.3/intero-0.1.38/elisp/intero.el
/home/jeff/.stack/global-project/.stack-work/install/x86_64-linux/ghc-8.6.3/8.6.3/share/x86_64-linux-ghc-8.6.3/intero-0.1.36/elisp/intero.el
/home/jeff/.stack/global-project/.stack-work/install/x86_64-linux/ghc-8.4.3/8.4.3/share/x86_64-linux-ghc-8.4.3/intero-0.1.38/elisp/intero.el
/home/jeff/.stack/global-project/.stack-work/install/x86_64-linux/ghc-8.4.4/8.4.4/share/x86_64-linux-ghc-8.4.4/intero-0.1.38/elisp/intero.el
/home/jeff/.emacs.d/elpa/intero-20190109.2039/intero.el
/home/jeff/code/hask-libs/intero/elisp/intero.el
```

I changed the definition of `intero-package-version` in  `/home/jeff/.emacs.d/elpa/intero-20190109.2039/intero.el` to this:
```
(defcustom intero-package-version
  (cl-case system-type
    ;; Until <https://github.com/haskell/network/issues/313> is fixed:
    (windows-nt "0.1.40")
    (cygwin "0.1.40")
    (t "0.1.40"))
  "Package version to auto-install.
```
(before the edits, it was at 0.1.38), but that didn't help. Should I change one of the files in `.stack/global-project/`? (None of those say "GHC 8.6.5".)

```
Intero is not installed in the Stack environment.

Installing intero-0.1.38 for GHC 8.6.5 ...

Invalid flag specification:
- Package 'haskeline' not found (specified on command line)

Could not install Intero!

We don't know why it failed. Please read the above output and try
installing manually. If that doesn't work, report this as a
problem.

Guess: You might need the "tinfo" package, e.g. libtinfo-dev.
```

**Comment by schuermannator** [comment]
Hm. It does seem it is installing the incorrect intero version. There are sometimes cached versions of the package that will result in the behavior you are observing (like changing the value but not seeing that reflected when it runs) do you have a `.local` folder that is possibly holding some cached content?

**Comment by AlexN34** [comment]
I'm also running into this even with hardcoding the intero version to `0.1.40` in `intero.el` - have tried deleting `~/.stack` and letting it install, manually installing intero first and checking `~/.local/*` is free of `intero` and `haskeline` respectively (assuming that's what was meant by cached content) to no avail. 
Any indications on what to try from here? 

Thanks in advance.

**Comment by schuermannator** [comment]
There is likely another cache somewhere, can you check in `.emacs.d`

**Comment by AlexN34** [comment]
I went with the nuclear option of deleting `.emacs.d/elpa` and redownloading *all* packages on startup, which seems to have worked - this time it compiled `intero` from scratch just fine. Thanks!

**Comment by schuermannator** [comment]
Haha great, glad it worked!

**Comment by JeffreyBenjaminBrown** [comment]
I went even more nuclear -- accidentally destroyed my system trying to use Wine for audio.

I've reinstalled `Kubuntu 18.04` from scratch, and `emacs`, `libtinfo-dev`, `stack`, and (from within emacs) `intero` (the within-emacs package list interface says it's installed). But I'm running into the same error I was getting before -- when I create a new .hs file in an empty folder, intero is not finding haskeline. 

Here's the full error message:

```
Intero is not installed in the Stack environment.

Installing intero-0.1.39 for GHC 8.6.5 ...

Invalid flag specification:
- Package 'haskeline' not found (specified on command line)

Could not install Intero!

gWe don't know why it failed. Please read the above output and try
installing manually. If that doesn't work, report this as a
problem.

Guess: You might need the "tinfo" package, e.g. libtinfo-dev.

WHAT TO DO NEXT

If you don't want to Intero to try installing itself again for
this project, just keep this buffer around in your Emacs.

If you'd like to try again next time you try use an Intero
feature, kill this buffer.
```
