### ISSUE TITLE
sqlite-based architecture

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/intero#630]
I had the crazy idea while on vacation that perhaps intero's architecture could be drastically changed to be SQL-based.

Rather than a continuous running process that's talked to over pipe or network, it could instead be run on demand to recompile a given file, and it would write the results to e.g. an sqlite database.

Then editors like Emacs or whatever could query the sqlite database for errors, type info, location info, etc.  this would solve a few problems: 
1. reduce memory use completely, 
2. getting information "offline", even when the compiler isn't working for whatever reason, 
3. having a standard format for querying (sql) with a schema that documents itself, allowing to delete a lot of code about communication, protocol, formats, etc. usually used for "LSP"-like behavior and 
4. allow concurrent requests for information out of the box.
5. It would also make reproducing issues MUCH easier. Because all Emacs would have to do would be to launch intero with stack as usual. If it works, then the rest of all issues would be "I queried the DB and didn't get what I wanted." Rather than what we have now with a lot of communication issues.

However, I'm not sure I will ever do this. It's just a thought.

**Comment by chrisdone** [comment]
## Problems:

* Existing IDE integrations exist:
  * Using the piped architecture
  * Using the `:foo` commandline interface

## Solutions

**Compatiblity layer:**

  * The new binary would be e.g. `intero2` and the old `intero` binary would be the compatibility layer.
  * `intero` would talk to sqlite for `:type-at`, etc., and call `intero2` periodically when `:load` or `:reload` is sent.
* Eventually we would delete the `intero` binary from the project when IDE integrations have moved over to `intero2`.

This would require writing the code for the compatibility layer and
maintaining that for a while, which isn't awesome. It can also be
confusing.

**Just make a new binary name:**

* Just stop making more releases of `intero` (except maybe upper bound bumps).
* Start releases of a fresh package `intero2` which new versions of
  the Emacs package would use.

This is quite good because it expresses a linear, new direction.

**An entirely different repo/project:**

* Start a fork codebase called intero2 (or a new name e.g. `nutero`) that represents the combination of the new architecture binary and Emacs as the reference implementation of IDE integration.
* Or actually include all IDE integrations directly in the repo.

I'm leaning towards this.

**Comment by chrisdone** [comment]
Issues that would be fixed by this:

* https://github.com/chrisdone/intero/issues/620
* https://github.com/chrisdone/intero/issues/625
* https://github.com/chrisdone/intero/issues/626 
* https://github.com/chrisdone/intero/issues/617
* https://github.com/chrisdone/intero/issues/566
* https://github.com/chrisdone/intero/issues/84

**Comment by purcell** [comment]
Seems there's some overlap here with the latest developments in `hie`, which is also starting to write out SQLite info about the codebase: https://www.haskell.org/ghc/blog/20190626-HIEFiles.html

**Comment by chrisdone** [comment]
Yeah, I saw that on reddit. Seems like everything is already going in this direction. 

I'd prefer it not require a special commandline tool to query it - an sqlite database is already queryable out of the box with SQL. But perhaps it's just a plain sqlite file with no binary wrapping. In any case, I like the direction.

**Comment by wz1000** [comment]
> I'd prefer it not require a special commandline tool to query it

HieDb is designed to be usable as a library, which you can use to query the database. You can also query the database yourself using SQL. 

The idea here is for SQLite to store "global" information that should be applicable across modules. As of now, there are just two tables in the database - one captures reference information for exported identifiers, and the other maintains a mapping of modules to `.hie` files. For information "local" to a given module, like type at a point, references of a local name,  the definition of names etc. you can just use the `.hie` file to answer your queries. HieDb can help in this case to figure out the location of the `.hie` file for a given module.

BTW, you had asked about "Tracking down instances from use-sites" on the ghc-devs list once. That inspired me to finally implement this, and put the info in `.hie` files. See [this GHC MR](https://gitlab.haskell.org/ghc/ghc/merge_requests/1286/). For a concrete example of how you can use this, take a look at the `HieQueries.hs` testcase and the corresponding `HieQueries.stdout` file.

**Comment by chrisdone** [comment]
Great! I'll have to give it a try once 8.8 comes around!

The main thing I'm mindful of with IDE integrations after doing a few different approaches (dumb output buffers in the IDE, screenscraping error messages as in flycheck, JSON services, or `:foo` command/reply style of GHCi), one fact that will remain the same is that Haskellers use various IDEs: Emacs, Vim, NeoVim, Visual Studio Code, Eclipse, JetBrains and SublimeText. Even Atom sees use. 

So while there might be a nice Haskell API to read the `.hie` files - the problem isn't solved as much as pushed towards the `hiedb` commandline tool, which will end up being the interface that tools talk to, because they don't speak Haskell. They're written in vimscript, or Emacs Lisp, or Python, or JavaScript. So you will effectively encourage use of this binary tool.

Ideally, you'd push it farther back into HIE and have all your IDEs talk over LSP. I looked at the LSP spec last year and did not feel like redoing what is already quite simple in Intero, in a complicated protocol. Alan has worked hard for a long time on HIE to bring LSP support. Ultimately, I hope reliable support will come generally and by that point I can retire Intero in favor of HIE. But at present I wouldn't say that LSP is a sure bet. It's what the industry wants, or thinks is the right way forward. I'm not sure. Languages are different and there'll be plenty of extensions to support the differentiating features. It's great to have a base, but a base would ideally be simple. But LSP isn't.

Meanwhile, SQL is by nature structured with an explicit schema. sqlite already has language integrations, via ODBC, the sqlite C API, and via simply the `sqlite3` binary. The extra part is that the query language is advanced, supports joins and manipulation, and everyone knows the language. Just consider e.g. "count how many expressions use this type across the project". You can do this via `point-types` or something more like Intero's `all-types` on every module and then filter and count them in your Elisp/JavaScript/Python code. Or, just do `SELECT COUNT(*) FROM point_type where type = ..` etc. And the answer will come back instantly.

Tooling is expensive, but the community has no monetary backing, so the end product isn't of a great quality. We tend to get balls of mud. So given that, I'd prefer that any integration like this be as minimal as possible (such as querying `hiedb` or `sqlite3`), with the minimum maintenance required.

So I see these scenarios:

1. Visual Studio Code users (and eventually Emacs users) will access this information via LSP. 
2. Vim (and similar) users will access this information via `hiedb` because LSP is too much hassle.
3. Potentially, the second type of users will access via the SQL interface, to gain more querying power.

I have to think more about whether I personally want to be in (1) or (3).

**Comment by lorenzo** [comment]
@chrisdone how come is using LSP too much hassle for vim users?

**Comment by chrisdone** [comment]
@lorenzo https://www.reddit.com/r/vim/comments/b3yzq4/a_lsp_client_maintainers_view_of_the_lsp_protocol/

**Comment by lorenzo** [comment]
@chrisdone since the Coc.nvim plug-in, I can say that the LSP experience in him is stellar, and probably as good as it is in VS code. The pain of supporting the LSP features is on the client and only needs to be implemented once (something that coc.nvim) did, server implementations just need to expose the functionality.

**Comment by asheshambasta** [comment]
@chrisdone in relation to #620; some writeup on how intero works would be good in order to suggest any ideas/improvements and taking a shot at it myself. As I understand, you're suggesting the sqlite based approach here since it seems that the caching seems to be an issue. I see two broad areas that I think I face issues with intero:
- memory footprint 
- lag 

As I pointed out in #620, apart from the high memory footprint, I also face regularly laggy typing. To be able to suggest any improvements, or taking a shot, if you can point me to where I can understand this better, that'd help.
