### ISSUE TITLE
Flickering after eldoc fontification

### ISSUE THREAD

**Issue by j0ni** [chrisdone/intero#636]
I noticed that after eldoc displays a message in the minibuffer, the entire frame would redraw/flicker. Moving around the buffer, this was happening all the time.

I dug into it, and was able to stop it happening by removing the fontification step in the `intero-eldoc` function.

Digging further, I managed to reduce it to the invocation of `haskell-mode` in the `intero-fontify-expression` function. Removing that invocation made the flicker go away, though it left the rendered message unfontified.

I ultimately replaced the `haskell-mode` invocation with the minimal bits that seemed necessary from that mode, and now it seems to be fontifying without flickering. So the fontification function looks like this in my local copy of intero:

```elisp
(defun intero-fontify-expression (expression)
  "Return a haskell-fontified version of EXPRESSION."
  (intero-with-temp-buffer
    (when (fboundp 'haskell-mode)
      (setq-local font-lock-defaults
                  '((haskell-font-lock-keywords)
                    nil nil nil nil
                    (font-lock-syntactic-face-function . haskell-syntactic-face-function)
                    ;; Get help from font-lock-syntactic-keywords.
                    (parse-sexp-lookup-properties . t)
                    (font-lock-extra-managed-props . (composition haskell-type))))
      ;; Preprocessor definitions can have backslash continuations
      (setq-local font-lock-multiline t))
    (insert expression)
    (if (fboundp 'font-lock-ensure)
        (font-lock-ensure)
      (font-lock-fontify-buffer))
    (buffer-string)))
```

Clearly this will become inconsistent with any changes to how `haskell-mode` configures fontification, but it works for me for now. I'd love a more considered fix, but I wouldn't be surprised if this isn't a problem for other people. I've had all manner of flickering issues around eldoc in the past, and whenever I google up such things, most of the content seems to be people commenting with variants of "works for me". So just in case it doesn't work for you, this might :smile:

OTOH maybe I'll be along again in a minute to tell you it was just a coincidence and the flicker is back. :man_shrugging:

**Comment by purcell** [comment]
Nice, thanks for looking into this! I'd be a little bit wary of reproducing so much low-level fontification code from `haskell-mode`. I noticed the old code was binding `haskell-mode-hook` to nil, but that's still not enough to short-circuit minor modes like `flycheck`, so I wonder if the following reformulation avoids the flicker for you:

```el
(defun intero-fontify-expression (expression)
  "Return a haskell-fontified version of EXPRESSION."
  (intero-with-temp-buffer
   (insert expression)
   (when (fboundp 'haskell-mode)
     (delay-mode-hooks (haskell-mode))
     (if (fboundp 'font-lock-ensure)
         (font-lock-ensure)
       (font-lock-fontify-buffer)))
   (buffer-string)))
```

**Comment by j0ni** [comment]
@purcell yep, that works for me! Fontification happens, but no flicker.

Thanks a bunch. And also for explaining why that works, I suspect this will turn out to be useful to know for inevitable later problem-solving :sweat_smile:

**Comment by purcell** [comment]
Thanks @j0ni, I've just committed that fix, then!
